# Generated by Django 5.2.15 on 2026-06-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_clinic_appointment_service_ref'),
        ('core', '0003_clinic_booking_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.practitioner'),
        ),
    ]
