# Generated by Django 5.2.15 on 2026-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_portal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='client',
            name='insurance_group_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='insurance_member_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='insurance_plan_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='insurance_relationship',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('spouse', 'Spouse'), ('dependent', 'Dependent')], default='self', max_length=20),
        ),
    ]
