# Generated by Django 5.2.15 on 2026-06-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_insurance_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sms_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='sms_opt_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
