# Generated by Django 5.2.15 on 2026-06-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_practitioner'),
        ('payments', '0002_payment_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('deposit', 'Deposit'), ('card_on_file', 'Card on file'), ('full_payment', 'Full payment')], default='invoice', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('square', 'Square'), ('manual', 'Manual')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_setup_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
