# Generated by Django 5.2.15 on 2026-06-04 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status'),
        ('clients', '0004_client_insurance_company_and_more'),
        ('core', '0004_clinic_noshow_fee_cents_and_more'),
        ('payments', '0003_payment_appointment_payment_checkout_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('telus', 'TELUS eClaims'), ('manual', 'Manual / Paper')], default='telus', max_length=20)),
                ('claim_number', models.CharField(blank=True, max_length=80)),
                ('service_date', models.DateField()),
                ('diagnosis_code', models.CharField(blank=True, max_length=20)),
                ('service_code', models.CharField(blank=True, default='21000', max_length=20)),
                ('amount_submitted_cents', models.PositiveIntegerField()),
                ('amount_approved_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('response_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims', to='appointments.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='clients.client')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='core.clinic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
