# Generated by Django 5.2.15 on 2026-06-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_clinic_appointment_service_ref'),
        ('core', '0002_clinic_intaketemplate_intakeresponse_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='booking_payment_mode',
            field=models.CharField(choices=[('none', 'No payment required'), ('deposit', 'Deposit'), ('card_on_file', 'Card on file'), ('full_payment', 'Full payment')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='clinic',
            name='card_on_file_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='payment_provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('square', 'Square')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('completed', 'Completed'), ('needs_review', 'Needs review')], default='sent', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('clinic_owner', 'Clinic Owner'), ('practitioner', 'Practitioner'), ('admin', 'Admin'), ('client', 'Client')], default='clinic_owner', max_length=30),
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioners', to='core.clinic')),
                ('services', models.ManyToManyField(blank=True, related_name='practitioners', to='core.service')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PractitionerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='core.practitioner')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('confirmation', 'Confirmation'), ('48_hour', '48 hour reminder'), ('same_day', 'Same day reminder')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.clinic')),
            ],
            options={
                'ordering': ['scheduled_for'],
                'unique_together': {('appointment', 'kind', 'channel')},
            },
        ),
    ]
