# Generated by Django 5.2.15 on 2026-06-04 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_insurance_company_and_more'),
        ('core', '0003_clinic_booking_payment_mode_and_more'),
        ('payments', '0003_payment_appointment_payment_checkout_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='noshow_fee_cents',
            field=models.PositiveIntegerField(default=5000, help_text='Fee charged when client no-shows'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='noshow_protection_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='reminder_email',
            field=models.EmailField(blank=True, help_text='From address for outgoing reminder emails', max_length=254),
        ),
        migrations.AddField(
            model_name='clinic',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('sessions', models.PositiveIntegerField(default=5)),
                ('validity_days', models.PositiveIntegerField(default=365, help_text='Days from purchase before package expires')),
                ('price_cents', models.PositiveIntegerField(default=50000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.clinic')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='core.service')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=160)),
                ('sessions_total', models.PositiveIntegerField()),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('price_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('exhausted', 'Exhausted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='clients.client')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_packages', to='core.clinic')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='payments.payment')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_instances', to='core.package')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('booked', 'Booked'), ('expired', 'Expired')], default='waiting', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='clients.client')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.clinic')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='core.practitioner')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.service')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
