# Generated by Django 5.2.15 on 2026-06-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clinic_noshow_fee_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Break/buffer time inserted after each slot'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Default appointment slot length'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='slot_duration_options',
            field=models.JSONField(blank=True, default=list, help_text='Selectable slot lengths, e.g. [30, 60, 90]'),
        ),
    ]
