# Generated by Django 5.2.15 on 2026-06-05 15:40

import uuid
from django.db import migrations, models


def backfill_tokens(apps, schema_editor):
    IntakeResponse = apps.get_model("core", "IntakeResponse")
    for response in IntakeResponse.objects.all():
        response.token = uuid.uuid4()
        response.save(update_fields=["token"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_practitioner_buffer_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeresponse',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Add token as non-unique first, backfill unique values, then enforce uniqueness.
        migrations.AddField(
            model_name='intakeresponse',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(backfill_tokens, noop),
        migrations.AlterField(
            model_name='intakeresponse',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_intake',
            field=models.BooleanField(default=False, help_text='Auto-send an intake/consent form when this service is booked'),
        ),
    ]
