# Generated by Django 5.2.15 on 2026-06-10 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_intakeresponse_reminder_sent_at_intakeresponse_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeresponse',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(max_length=10)),
                ('resource', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=255)),
                ('object_ref', models.CharField(blank=True, max_length=64)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource', 'created_at'], name='core_auditl_resourc_3c6502_idx'), models.Index(fields=['actor', 'created_at'], name='core_auditl_actor_i_41600a_idx')],
            },
        ),
    ]
